defaultcontentlanguage = "en"
languagecode = "en"
theme = "hugo-coder"
title = "Paulo Salgado"

[params]
  author = "Paulo Salgado"
  avatarurl = "images/avatar.png"
  colorScheme = "auto"
  description = "Hello, World!"
  favicon_16 = "images/favicon-16.png"
  favicon_32 = "images/favicon-32.png"
  info = "Software Developer"

  [[params.social]]
    icon = "fas fa-envelope fa-2x"
    name = "E-mail"
    url = "mailto:pjosalgado@gmail.com"
    weight = 1

  [[params.social]]
    icon = "fab fa-github fa-2x"
    name = "GitHub"
    url = "https://github.com/pjosalgado"
    weight = 2

  [[params.social]]
    icon = "fab fa-gitlab fa-2x"
    name = "GitLab"
    url = "https://gitlab.com/pjosalgado"
    weight = 3

  [[params.social]]
    icon = "fab fa-keybase fa-2x"
    name = "Keybase"
    url = "https://keybase.io/pjosalgado"
    weight = 4

  [[params.social]]
    icon = "fab fa-linkedin fa-2x"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/pjosalgado"
    weight = 5

[languages]
  [languages.en]
    languageName = ":uk:"

  [languages.pt-br]
    languageName = ":brazil:"
    [languages.pt-br.params]
      info = "Desenvolvedor de Software"
